# Generated by Django 5.1.3 on 2024-11-06 09:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_app', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 11, 6, 9, 51, 54, 88266))),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('file_name', models.CharField(max_length=200)),
                ('file_path', models.CharField()),
                ('user_app', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.userclient')),
            ],
        ),
        migrations.CreateModel(
            name='AppealApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appeal', models.CharField(choices=[('added', 'Добавление'), ('extended', 'Расширение'), ('duplicate', 'Дубликат')], max_length=20)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeal', to='product_app.application')),
            ],
        ),
        migrations.CreateModel(
            name='CoordinationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordination', models.CharField(choices=[('material_not_added', 'Материал не выбран'), ('coordination_no_required', 'Согласование не требуется'), ('extended_after_coordination', 'Расширение после согласования'), ('extended_without_coordination', 'Расширение без согласования')], max_length=50)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordination', to='product_app.application')),
            ],
        ),
        migrations.CreateModel(
            name='StatusApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sent_for-processing', 'Отправлена в обработку'), ('returned_for_clarification', 'Возвращена на уточнение'), ('sent_for_processing_repeated', 'Отправлена в обработку (повторно)'), ('processing_completed', 'Обработка завершена'), ('in_process_repeated', 'В обработке (повторно)'), ('in_process_confirmed', 'В обработке (подтверждена)')], max_length=50)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='product_app.application')),
            ],
        ),
        migrations.CreateModel(
            name='TimeToProcessingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_from_request_to_processing', models.CharField(default='Обработка не завершена', max_length=200)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='time_to_processing', to='product_app.application')),
            ],
        ),
    ]
