# Generated by Django 5.1.3 on 2024-11-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
