# Generated by Django 5.1.3 on 2024-11-06 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_alter_application_created_at'),
        ('users', '0002_remove_userclient_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('hash', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Hash',
                'verbose_name_plural': 'Hashes',
            },
        ),
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads_model')),
            ],
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
        migrations.RemoveField(
            model_name='application',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='file_path',
        ),
        migrations.AddField(
            model_name='appealapplication',
            name='appel_view',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='appealapplication',
            name='appeal',
            field=models.CharField(choices=[('added', 'Добавление'), ('extended', 'Расширение'), ('duplicate', 'Дубликат')], max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='user_app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_app', to='users.userclient'),
        ),
        migrations.AddField(
            model_name='application',
            name='hash_data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hash_data', to='product_app.packagehash'),
        ),
    ]
