# Generated by Django 5.1.3 on 2024-11-06 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_packagehash_uploadfiles_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appealapplication',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='product_app.application'),
        ),
    ]
