# Generated by Django 5.1.3 on 2024-11-06 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_alter_appealapplication_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appealapplication',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeal', to='product_app.application'),
        ),
    ]
