# Generated by Django 5.1.3 on 2024-11-07 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_alter_appealapplication_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppealBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appel', models.CharField(choices=[('added', 'Добавление'), ('extended', 'Расширение'), ('duplicate', 'Дубликат')], default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CoordinationBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordination', models.CharField(choices=[('material_not_added', 'Материал не выбран'), ('coordination_no_required', 'Согласование не требуется'), ('extended_after_coordination', 'Расширение после согласования'), ('extended_without_coordination', 'Расширение без согласования')], default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StatusBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sent_for-processing', 'Отправлена в обработку'), ('returned_for_clarification', 'Возвращена на уточнение'), ('sent_for_processing_repeated', 'Отправлена в обработку (повторно)'), ('processing_completed', 'Обработка завершена'), ('in_process_repeated', 'В обработке (повторно)'), ('in_process_confirmed', 'В обработке (подтверждена)')], default='', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='appealapplication',
            name='appeal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeal_book', to='product_app.appealbook'),
        ),
        migrations.AlterField(
            model_name='coordinationapplication',
            name='coordination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordination_book', to='product_app.coordinationbook'),
        ),
        migrations.AlterField(
            model_name='statusapplication',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_book', to='product_app.statusbook'),
        ),
    ]
