# Generated by Django 5.1.3 on 2024-11-07 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0006_appealbook_coordinationbook_statusbook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appealapplication',
            name='appeal',
        ),
        migrations.RemoveField(
            model_name='coordinationapplication',
            name='coordination',
        ),
        migrations.RemoveField(
            model_name='statusapplication',
            name='status',
        ),
        migrations.AddField(
            model_name='appealapplication',
            name='appeal_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appeal_book', to='product_app.appealbook'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coordinationapplication',
            name='coordination_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coordination_book', to='product_app.coordinationbook'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statusapplication',
            name='status_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='status_book', to='product_app.statusbook'),
            preserve_default=False,
        ),
    ]
