# Generated by Django 5.1.3 on 2024-11-07 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0007_remove_appealapplication_appeal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appealbook',
            old_name='appel',
            new_name='appeal',
        ),
    ]
