# Generated by Django 5.1.3 on 2024-11-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0008_rename_appel_appealbook_appeal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appealapplication',
            old_name='appel_view',
            new_name='appeal_view',
        ),
        migrations.AlterField(
            model_name='coordinationbook',
            name='coordination',
            field=models.CharField(choices=[('material_not_added', 'Материал не выбран'), ('coordination_no_required', 'Согласование не требуется'), ('extended_after_coordination', 'Расширен после согласования'), ('extended_without_coordination', 'Расширен без согласования')], default='', max_length=200),
        ),
    ]
